export default {
  TRENDING_LIST: 'TRENDING_LIST',
  PROFILE: 'PROFILE',
  CLIENTS: 'CLIENTS',
  ARTICLE_LIST: 'ARTICLE_LIST',
  CHAT_LIST: 'CHAT_LIST',
  CHAT: 'CHAT',
  T_GOAL_LIST: 'T_GOAL_LIST',
  T_GOAL: 'T_GOAL',
  STORY_CHAT: 'STORY_CHAT',
  BOT_CHAT: 'BOT_CHAT',
  TOOL: 'TOOL',
  ADD_STORY: 'ADD_STORY'
}